// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: addressbook.proto

package tutorial

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Person) Validate() error {
	if this.Phones != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Phones); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Phones", err)
		}
	}
	if this.LastUpdated != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.LastUpdated); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("LastUpdated", err)
		}
	}
	return nil
}
func (this *Person_PhoneNumber) Validate() error {
	if this.Number == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Number", fmt.Errorf(`value '%v' must not be an empty string`, this.Number))
	}
	return nil
}
func (this *AddressBook) Validate() error {
	for _, item := range this.People {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("People", err)
			}
		}
	}
	return nil
}
