all: build-in-funcs build-in-vars

build-in-funcs:
    @echo "build in fucntions:"
    @echo $(realpath ..)

build-in-vars:
    @echo "build in vars:"
    @echo "MAKEFILES: ${MAKEFILES}"
    @echo "VPATH: ${VPATH}"
    @echo "SHELL: ${SHELL}"
    @echo "MAKESHELL: ${MAKESHELL}"
    @echo "CURDIR: ${CURDIR}"
