all: build-in-directives build-in-funcs build-in-vars

build-in-directives:
	@echo "hello"

build-in-funcs:
	@echo "build in fucntions:"
	@echo $(realpath ..)

build-in-vars:
	@echo "build in vars:"
	@echo "MAKEFILES: ${MAKEFILES}"
	@echo "VPATH: ${VPATH}"
	@echo "SHELL: ${SHELL}"
	@echo "MAKESHELL: ${MAKESHELL}"
	@echo "MAKE_VERSION: ${MAKE_VERSION}"
	@echo "MAKE_HOST: ${MAKE_HOST}"
	@echo "MAKE_LEVEL: ${MAKE_LEVEL}"
	@echo "MAKEFLAGS: ${MAKEFLAGS}"
	@echo "GNUMAKEFLAGS: ${GNUMAKEFLAGS}"
	@echo "CURDIR:${CURDIR}"
